### ISSUE TITLE
Redis database running before starting this project...

### ISSUE THREAD

**Issue by zapjelly** [spring-guides/gs-spring-data-reactive-redis#2]
In case this is any help to anyone trying this project

make sure to install and start redis database before starting this project :)
https://medium.com/@petehouston/install-and-config-redis-on-mac-os-x-via-homebrew-eb8df9a4f298

**Comment by Xarvalus** [comment]
Minimal config for Docker (docker-compose.yml)

```
version: '3'

volumes:
  dbdata_redis:
    driver: local

services:
  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379:6379
    volumes:
      - dbdata_redis:/data
    command:
      - --appendonly yes
```
